server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    create-schemas: true
    default-schema: ${DB_SCHEMA:public}
    schemas: ${DB_SCHEMA:public}

  # Vault va Cloud tekshiruvlarini production da o'chirish
  cloud:
    vault:
      enabled: false
    compatibility-verifier:
      enabled: false

app:
  cors:
    allowed-origins: ${CORS_ORIGINS:}

logging:
  level:
    root: INFO
    uz.familyfinance: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
